### ISSUE TITLE
Broken lua filepaths when transpiled/bundled 

### ISSUE THREAD

**Issue by joeyfigaro** [conveyor-mq/conveyor-mq#114]
Thank you for your work on this! I've enjoyed working with it so far.

I'm having trouble bundling up my app, unfortunately. `ts-node` is the only thing I've managed to use to successfully start up while using conveyor-mq. I've been trying to use `@vercel/ncc` for running and building, but it's complaining about what looks like lua script path issues and a pretty generic `cannot read property apply of undefined`:

```sh
// Cannot read property apply of undefined
(node:65991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)
(node:65991) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of undefined
    at Object.module.exports.__webpack_modules__.7966.exports.callLuaScriptMulti (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/utils/redis.js:63:1)
    at Object.module.exports.__webpack_modules__.5059.exports.enqueueTaskMulti (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/actions/enqueue-task.js:66:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/actions/enqueue-tasks.js:49:1
    at arrayMap (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/lodash/lodash.js:639:1)
    at Function.map (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/lodash/lodash.js:9580:1)
    at Object.module.exports.__webpack_modules__.7941.exports.enqueueTasksMulti (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/actions/enqueue-tasks.js:48:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/actions/enqueue-tasks.js:64:1
    at step (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/actions/enqueue-tasks.js:33:1)
    at Object.next (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/actions/enqueue-tasks.js:14:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/actions/enqueue-tasks.js:8:1
```

```sh
// lua issues
(node:65991) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/4c6aaadb4085edb0fcc4f2b833290d23/mark-task-processing.lua'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:95:1
    at step (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:33:1)
    at Object.next (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:14:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:8:1
    at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.5406.__awaiter (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:4:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:92:1
    at arrayEach (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/lodash/lodash.js:516:1)
(node:65991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)
(node:65991) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/4c6aaadb4085edb0fcc4f2b833290d23/enqueue-scheduled-tasks.lua'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:95:1
    at step (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:33:1)
    at Object.next (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:14:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:8:1
    at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.5406.__awaiter (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:4:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:92:1
    at arrayEach (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/lodash/lodash.js:516:1)
(node:65991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
(node:65991) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/4c6aaadb4085edb0fcc4f2b833290d23/acknowledge-orphaned-processing-tasks.lua'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:95:1
    at step (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:33:1)
    at Object.next (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:14:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:8:1
    at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.5406.__awaiter (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:4:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:92:1
    at arrayEach (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/lodash/lodash.js:516:1)
(node:65991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
(node:65991) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/4c6aaadb4085edb0fcc4f2b833290d23/update-task.lua'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:95:1
    at step (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:33:1)
    at Object.next (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:14:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:8:1
    at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.5406.__awaiter (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:4:1)
    at /private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/conveyor-mq/dist/lua/index.js:92:1
    at arrayEach (/private/var/folders/y5/cvt3hflx0q1byk56f9t3ntbh0000gn/T/webpack:/@groupic/jobs/node_modules/lodash/lodash.js:516:1)
```

---

Edit: transpiled with plain old `tsc` and getting the same result. The errors are a lot more friendly/readable, though:

```sh
(node:70375) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/update-task.lua'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at /Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/index.js:5012:39
    at step (/Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/index.js:4950:23)
    at Object.next (/Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/index.js:4931:53)
    at /Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/index.js:4925:71
    at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.4369.__awaiter (/Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/index.js:4921:12)
    at /Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/index.js:5009:16
    at arrayEach (/Users/joeyfigaro/repositories/groupic/packages/jobs/_dist/index.js:13946:11)
```

**Comment by joeyfigaro** [comment]
[May be relevant](https://github.com/vercel/ncc/issues/575#issuecomment-674292466)

**Comment by joeyfigaro** [comment]
For anyone else who lands here, I ended up just copying the relevant lua scripts over to my out/bundle directory. Works for now.

**Comment by dougg0k** [comment]
I usually use copyfiles when bundling typescript for non-ts files to build folder.

https://github.com/calvinmetcalf/copyfiles

e.g.,
`copyfiles --up 1 src/services/proto/*.proto build/`

**Comment by jasrusable** [comment]
Should now be fixed since https://github.com/conveyor-mq/conveyor-mq/pull/166. Thanks @dougg0k :)
